from abyan_project_automation.src.andriod.pages.cash_portfolios_creation_page import CreateCashPortfolios
from abyan_project_automation.src.andriod.pages.deposit_cases_cash_portfolio_page import DepositCashPortfolio
from abyan_project_automation.src.andriod.pages.deposit_cases_investment_portfolios_page import \
    DepositInvestmentPortfolio
from abyan_project_automation.src.andriod.pages.deposit_cases_jadwa_portfolio_page import DepositJadwaPortfolio
from abyan_project_automation.src.andriod.pages.login_page import LoginPage
from abyan_project_automation.src.andriod.pages.update_cash_portfolios_page import UpdateCashPortfolios
from abyan_project_automation.src.constants.credentials import password
from abyan_project_automation.src.utils.driver_factory import create_driver


def test_deposit_in_conservative_portfolio_using_mada_and_hyperpay():
    """Verify successfully deposit in "conservative portfolio" using payment method Mada with payment gateway 'Hyperpay'."""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("584679799")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    cash_deposit_page = DepositCashPortfolio(driver)
    investment_deposit = DepositInvestmentPortfolio(driver)
    investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("beenishzia")
    investment_deposit.perform_click_action_on_deposit_button()
    cash_deposit_page.perform_click_action_on_mada_payment_card()
    cash_deposit_page.perform_click_action_on_amount_input_field()
    cash_deposit_page.input_deposit_amount(1000)
    cash_deposit_page.perform_click_action_on_view_screen()
    cash_deposit_page.perform_click_on_deposit_button()
    cash_deposit_page.enter_cvv_code()
    cash_deposit_page.click_on_screen_view_and_close_the_keyboard()
    cash_deposit_page.click_on_add_card_button()
    investment_deposit.click_on_browser_success_pay_button()
    cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
    # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
    cash_deposit_page.perform_scroll_down_and_click_first_transaction()
    cash_deposit_page.click_on_topmost_deposit_transaction()
    cash_deposit_page.verify_title_of_transection_detail_screen()
    cash_deposit_page.perform_scroll_down_on_screen()
    cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen() #Done

# def test_deposit_in_moderate_portfolio_using_mada_and_hyperpay():
#     """Verify successfully deposit in Cash "moderate portfolio" using payment method Mada with payment gateway 'Hyperpay'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("584679799")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("moderateportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     # cash_deposit_page.perform_click_action_on_deposit_button_and_navigate_next_screen()
#     cash_deposit_page.perform_click_action_on_mada_payment_card()
#     cash_deposit_page.perform_click_action_on_amount_input_field()
#     cash_deposit_page.input_deposit_amount(50)
#     cash_deposit_page.perform_click_action_on_view_screen()
#     cash_deposit_page.perform_click_on_deposit_button()
#     cash_deposit_page.enter_cvv_code()
#     cash_deposit_page.click_on_screen_view_and_close_the_keyboard()
#     cash_deposit_page.click_on_add_card_button()
#     investment_deposit.click_on_browser_success_pay_button()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen() #Done

# def test_deposit_in_growth_portfolio_using_mada_and_hyperpay():
#     """Verify successfully deposit in Cash "growth portfolio" using payment method Mada with payment gateway 'Hyperpay'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("584679799")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("growthportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     cash_deposit_page.perform_click_action_on_mada_payment_card()
#     cash_deposit_page.perform_click_action_on_amount_input_field()
#     cash_deposit_page.input_deposit_amount(50)
#     cash_deposit_page.perform_click_action_on_view_screen()
#     cash_deposit_page.perform_click_on_deposit_button()
#     # deposit_in_jadwa.click_on_payment_method_mada()
#     cash_deposit_page.enter_cvv_code()
#     cash_deposit_page.click_on_screen_view_and_close_the_keyboard()
#     cash_deposit_page.click_on_add_card_button()
#     investment_deposit.click_on_browser_success_pay_button()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen() #Done

# def test_deposit_in_conservative_portfolio_using_mada_and_money_hash():
#     """Verify successfully deposit in "conservative portfolio" using payment method Mada with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("584679799")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     #login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("conservativeportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     deposit_in_jadwa.click_on_payment_method_mada()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_mada_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number()
#     deposit_in_jadwa.click_on_pay_button()
#     cash_deposit_page.click_on_submit_button_on_demo_page()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen() #Done

# def test_deposit_in_moderate_portfolio_using_mada_and_money_hash():
#     """Verify successfully deposit in "moderate portfolio" using payment method Mada with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("584679799")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("growthportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     deposit_in_jadwa.click_on_payment_method_mada()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_mada_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number()
#     cash_deposit_page.click_on_screen_to_close_the_keyboard()
#     deposit_in_jadwa.click_on_pay_button()
#     cash_deposit_page.click_on_submit_button_on_demo_page()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen() #Done

# def test_deposit_in_growth_portfolio_using_mada_and_money_hash():
#     """Verify successfully deposit in "growth portfolio" using payment method Mada with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("584679799")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("growthportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     deposit_in_jadwa.click_on_payment_method_mada()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_mada_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number()
#     deposit_in_jadwa.click_on_pay_button()
#     cash_deposit_page.click_on_submit_button_on_demo_page()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen() #Done

# def test_deposit_in_conservative_portfolio_using_visa_master_and_money_hash():
#     """Verify successfully deposit in "conservative portfolio" using payment method Visa/Master with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("542525368")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_respective_portfolio_and_verify_home_screen("conservativeportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     cash_deposit_page.click_on_payment_method_visa_master()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_visa_master_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info_for_visa_card()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info_for_visa_master()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number_for_visa_master()
#     # cash_deposit_page.click_on_screen_to_close_the_keyboard()
#     deposit_in_jadwa.click_on_pay_button()
#     #cash_deposit_page.click_on_submit_button_on_demo_page()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen()

# def test_deposit_in_moderate_portfolio_using_visa_master_and_money_hash():
#     """Verify successfully deposit in "moderate portfolio" using payment method Visa/Master with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("542525368")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("moderateportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     cash_deposit_page.click_on_payment_method_visa_master()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_visa_master_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info_for_visa_card()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info_for_visa_master()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number_for_visa_master()
#     cash_deposit_page.click_on_screen_to_close_the_keyboard()
#     deposit_in_jadwa.click_on_pay_button()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen()

# def test_deposit_in_moderate_portfolio_using_visa_master_and_money_hash():
#     """Verify successfully deposit in Cash "moderate portfolio" using payment method Visa/Master with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("542525368")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     update_cash_page.click_on_pre_define_category_and_verify_home_screen("customcategory")
#     holistic_page.verify_pre_define_category_home_screen("customcategory")
#     cash_deposit_page.perform_click_action_on_deposit_button_and_navigate_next_screen()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     cash_deposit_page.click_on_payment_method_visa_master()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_visa_master_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info_for_visa_card()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info_for_visa_master()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number_for_visa_master()
#     cash_deposit_page.click_on_screen_to_close_the_keyboard()
#     deposit_in_jadwa.click_on_pay_button()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()

# def test_deposit_in_growth_portfolio_using_visa_master_and_money_hash():
#     """Verify successfully deposit in Cash "growth portfolio" using payment method Visa/Master with payment gateway 'MoneyHash'."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("542525368")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     update_cash_page.click_on_pre_define_category_and_verify_home_screen("predefinecash")
#     holistic_page.verify_pre_define_category_home_screen("predefinecash")
#     cash_deposit_page.perform_click_action_on_deposit_button_and_navigate_next_screen()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     deposit_in_jadwa.click_deposit_button()
#     cash_deposit_page.click_on_payment_method_visa_master()
#     deposit_in_jadwa.click_on_input_name_field_and_input_name()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_visa_master_card_number()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_field_and_input_expiry_month_info_for_visa_card()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_field_and_input_expiry_year_info_for_visa_master()
#     deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard()
#     deposit_in_jadwa.click_on_cvv_and_input_number_for_visa_master()
#     cash_deposit_page.click_on_screen_to_close_the_keyboard()
#     deposit_in_jadwa.click_on_pay_button()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()

def test_deposit_in_conservative_portfolio_using_visa_master_and_tap():
    """ Verify successfully deposit in "conservative portfolio" using payment method Visa/Master with payment gateway 'Tap'."""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("542525368")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    cash_deposit_page = DepositCashPortfolio(driver)
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    deposit_in_jadwa = DepositJadwaPortfolio(driver)
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("customcategory")
    holistic_page.verify_pre_define_category_home_screen("customcategory")
    cash_deposit_page.perform_click_action_on_deposit_button_and_navigate_next_screen()
    deposit_in_jadwa.click_on_payment_by_card_option()
    deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
    deposit_in_jadwa.input_deposit_amount(1000)
    deposit_in_jadwa.click_deposit_button()
    cash_deposit_page.click_on_payment_method_visa_master()
    deposit_in_jadwa.click_on_field_and_input_visa_master_card_number_for_tap()
    deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard_for_tap()
    deposit_in_jadwa.click_on_field_and_input_expiry_date_for_tap()
    deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard_for_tap()
    deposit_in_jadwa.click_on_cvv_and_input_number_for_visa_master_for_tap()
    deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard_for_tap()
    deposit_in_jadwa.click_on_input_name_field_and_input_name_for_tap()
    deposit_in_jadwa.click_on_screen_view_and_close_the_keyboard_for_tap()
    deposit_in_jadwa.click_on_pay_button_for_tap_and_money_hash()
    cash_deposit_page.click_on_success_button()
    cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
    cash_deposit_page.perform_scroll_down_and_click_first_transaction()
    cash_deposit_page.click_on_topmost_deposit_transaction()
    cash_deposit_page.verify_title_of_transection_detail_screen()

# def test_deposit_in_growth_portfolio_using_mada_and_money_hash():
#     """Verify successfully deposit in Cash "growth portfolio" using payment method Visa/Master with payment gateway 'Tap'"""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("542525368")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     cash_deposit_page = DepositCashPortfolio(driver)
#     update_cash_page = UpdateCashPortfolios(driver)
#     holistic_page = CreateCashPortfolios(driver)
#     deposit_in_jadwa = DepositJadwaPortfolio(driver)
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("growthportfolio")
#     investment_deposit.perform_click_action_on_deposit_button()
#     deposit_in_jadwa.click_on_payment_by_card_option()
#     deposit_in_jadwa.click_on_input_field_to_enter_amount_and_proceed()
#     deposit_in_jadwa.input_deposit_amount(1000)
#     investment_deposit.click_deposit_button_for_visamaster_payment()
#     investment_deposit.click_deposit_button_for_visamaster_payment()
#     investment_deposit.click_on_field_and_input_mada_card_number()
#     investment_deposit.click_on_field_and_input_expiry_date()
#     investment_deposit.click_on_cvv_and_input_number()
#     investment_deposit.click_on_input_name_field_and_input_name()
#     investment_deposit.click_on_pay_button()
#     # cash_deposit_page.click_on_submit_button_on_demo_page()
#     cash_deposit_page.perform_click_action_to_close_the_deposit_screen()
#     # cash_deposit_page.perform_click_action_to_close_the_recurring_pop_up()
#     cash_deposit_page.perform_scroll_down_and_click_first_transaction()
#     cash_deposit_page.click_on_topmost_deposit_transaction()
#     cash_deposit_page.verify_title_of_transection_detail_screen()
#     cash_deposit_page.perform_scroll_down_on_screen()
#     cash_deposit_page.click_back_button_to_move_primary_portfolio_home_screen()
#     cash_deposit_page.click_back_button_to_move_holistic_screen()
#     cash_deposit_page.perform_pull_down_to_refresh_the_screen()
#     update_cash_page.click_on_pre_define_category_and_verify_home_screen("growthportfolio")
