from abyan_project_automation.src.andriod.pages.deposit_cases_investment_portfolios_page import \
    DepositInvestmentPortfolio
from abyan_project_automation.src.andriod.pages.investment_portfolio_withdrawal_to_bank_page import \
    WithdrawalInvestmentPortfolios
from abyan_project_automation.src.andriod.pages.login_page import LoginPage
from abyan_project_automation.src.constants.credentials import password
from abyan_project_automation.src.utils.driver_factory import create_driver


def test_withdrawal_conservative_portfolio():
    """Verify user should successfully withdraw 100 SAR from Conservative portfolio by selecting the amount from given options"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("554846073")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    investment_portfolio_withdrawal = WithdrawalInvestmentPortfolios(driver)
    investment_portfolio_withdrawal.click_on_settings_button()
    investment_portfolio_withdrawal.click_on_orders_tab()
    investment_portfolio_withdrawal.click_on_withdrawal_funds_option()
    investment_portfolio_withdrawal.click_on_continue_withdrawal_button()
    investment_portfolio_withdrawal.select_portfolio_performance_option()
    investment_portfolio_withdrawal.click_on_continue_button()
    investment_deposit = DepositInvestmentPortfolio(driver)
    investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("Growth")
    investment_portfolio_withdrawal.click_on_continue_button()
    # investment_portfolio_withdrawal.click_on_hundred_option()
    # investment_portfolio_withdrawal.click_on_two_thousand_option()
    investment_portfolio_withdrawal.click_on_five_thousand_option()
    investment_portfolio_withdrawal.click_on_transfer_your_savings_button()
    investment_portfolio_withdrawal.click_on_transaction_completed_button()
    login_page.enter_password(password)
    login_page.enter_otp_code()
    investment_portfolio_withdrawal.click_on_home_button()
    # cancel withdrawal
    investment_portfolio_withdrawal.click_on_settings_button()
    investment_portfolio_withdrawal.click_on_orders_tab()
    investment_portfolio_withdrawal.click_on_cancel_existing_transaction()
    investment_portfolio_withdrawal.click_on_continue_button()
    investment_portfolio_withdrawal.click_on_delivery_between_guards()
    investment_portfolio_withdrawal.click_on_cancel_withdrawal_button()
    login_page.enter_password(password)
    login_page.enter_otp_code()
    investment_portfolio_withdrawal.click_on_home_button() #Done

# def test_withdrawal_moderate_portfolio():
#     """Verify user should successfully withdraw 100 SAR from Moderate portfolio by selecting the amount from given options"""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("554846073")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     investment_portfolio_withdrawal = WithdrawalInvestmentPortfolios(driver)
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_withdrawal_funds_option()
#     investment_portfolio_withdrawal.click_on_continue_withdrawal_button()
#     investment_portfolio_withdrawal.select_portfolio_performance_option()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("fffff")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_hundred_option()
#     investment_portfolio_withdrawal.click_on_transfer_your_savings_button()
#     investment_portfolio_withdrawal.click_on_transaction_completed_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
#     # cancel withdrawal
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_cancel_existing_transaction()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_delivery_between_guards()
#     investment_portfolio_withdrawal.click_on_cancel_withdrawal_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button() #Done

# def test_withdrawal_growth_portfolio():
#     """Verify user should successfully withdraw 100 SAR from Growth portfolio by selecting the amount from given options"""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("554846073")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     investment_portfolio_withdrawal = WithdrawalInvestmentPortfolios(driver)
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_withdrawal_funds_option()
#     investment_portfolio_withdrawal.click_on_continue_withdrawal_button()
#     investment_portfolio_withdrawal.select_portfolio_performance_option()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("Growth")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_hundred_option()
#     investment_portfolio_withdrawal.click_on_transfer_your_savings_button()
#     investment_portfolio_withdrawal.click_on_transaction_completed_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
#     # cancel withdrawal
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_cancel_existing_transaction()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_delivery_between_guards()
#     investment_portfolio_withdrawal.click_on_cancel_withdrawal_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button() #Done

# def test_withdrawal_complete_amount_from_conservative_portfolio():
#     """Verify user should successfully withdraw the 'complete' amount from Conservative portfolio to the user’s bank account"""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("554846073")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     investment_portfolio_withdrawal = WithdrawalInvestmentPortfolios(driver)
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_withdrawal_funds_option()
#     investment_portfolio_withdrawal.click_on_continue_withdrawal_button()
#     investment_portfolio_withdrawal.select_portfolio_performance_option()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("beenish")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_full_amount_option()
#     investment_portfolio_withdrawal.enter_full_portfolio_amount("beenish")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_transfer_your_savings_button()
#     investment_portfolio_withdrawal.click_on_transaction_completed_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
#     # cancel withdrawal
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_cancel_existing_transaction()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_delivery_between_guards()
#     investment_portfolio_withdrawal.click_on_cancel_withdrawal_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
# def test_withdrawal_complete_amount_from_moderate_portfolio():
#     """Verify user should successfully withdraw the complete amount from Moderate portfolio to the user’s bank account"""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("554846073")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     investment_portfolio_withdrawal = WithdrawalInvestmentPortfolios(driver)
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_withdrawal_funds_option()
#     investment_portfolio_withdrawal.click_on_continue_withdrawal_button()
#     investment_portfolio_withdrawal.select_portfolio_performance_option()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("Growth")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_full_amount_option()
#     investment_portfolio_withdrawal.enter_full_portfolio_amount("Growth")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_transfer_your_savings_button()
#     investment_portfolio_withdrawal.click_on_transaction_completed_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
#     # cancel withdrawal
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_cancel_existing_transaction()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_delivery_between_guards()
#     investment_portfolio_withdrawal.click_on_cancel_withdrawal_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
# def test_withdrawal_complete_amount_from_growth_portfolio():
#     """Verify user should successfully withdraw the complete amount from Growth portfolio to the user’s bank account"""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("554846073")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     investment_portfolio_withdrawal = WithdrawalInvestmentPortfolios(driver)
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_withdrawal_funds_option()
#     investment_portfolio_withdrawal.click_on_continue_withdrawal_button()
#     investment_portfolio_withdrawal.select_portfolio_performance_option()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_deposit = DepositInvestmentPortfolio(driver)
#     investment_deposit.click_on_conservative_portfolio_and_verify_home_screen("uninvested")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_full_amount_option()
#     investment_portfolio_withdrawal.enter_full_portfolio_amount("uninvested")
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_transfer_your_savings_button()
#     investment_portfolio_withdrawal.click_on_transaction_completed_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
#     # cancel withdrawal
#     investment_portfolio_withdrawal.click_on_settings_button()
#     investment_portfolio_withdrawal.click_on_orders_tab()
#     investment_portfolio_withdrawal.click_on_cancel_existing_transaction()
#     investment_portfolio_withdrawal.click_on_continue_button()
#     investment_portfolio_withdrawal.click_on_delivery_between_guards()
#     investment_portfolio_withdrawal.click_on_cancel_withdrawal_button()
#     login_page.enter_password(password)
#     login_page.enter_otp_code()
#     investment_portfolio_withdrawal.click_on_home_button()
#



    # investment_portfolio_withdrawal.click_on_keep_withdrawal_option()






