from abyan_project_automation.src.andriod.pages.change_investment_portfolio_types_page import \
    ChangeInvestmentPortfoliosType
from abyan_project_automation.src.andriod.pages.login_page import LoginPage
from abyan_project_automation.src.andriod.pages.update_investment_portfolios_page import UpdateInvestmentPortfolios
from abyan_project_automation.src.constants.credentials import password
from abyan_project_automation.src.utils.driver_factory import create_driver


def test_update_conservative_portfolios_name():
    """Case 1 Verify successfully update the Conservative Portfolio name and display the new name on the Conservative Portfolio Home Screen."""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_investment_portfolio = UpdateInvestmentPortfolios(driver)
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen("beenish")
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen("beenish")
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_investment_portfolio.click_on_the_edit_option()
    update_investment_portfolio.click_on_name_field_and_remove_to_update()
    update_investment_portfolio.click_on_the_view_to_hide_keyboard()
    update_investment_portfolio.click_on_icon_to_update()
    update_investment_portfolio.click_on_save_button()
    update_investment_portfolio.click_on_success_update_button()

# def test_update_conservative_portfolios_icon():
#     """Case 2 Verify successfully update the Conservative Portfolio goal icon and display it correctly on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_investment_portfolio = UpdateInvestmentPortfolios(driver)
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen("PortfolioVXR")
#     update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen("PortfolioVXR")
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_investment_portfolio.click_on_the_edit_option()
#     update_investment_portfolio.click_on_name_field_and_remove_to_update()
#     update_investment_portfolio.click_on_the_view_to_hide_keyboard()
#     update_investment_portfolio.click_on_icon_to_update()
#     update_investment_portfolio.click_on_save_button()
#     update_investment_portfolio.click_on_success_update_button()

# def test_hide_conservative_portfolios():
#     """Case 3 Verify successfully hide the Conservative Portfolio and ensure it is not visible on the Holistic Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("beenish")
#     update_jadwa_page.verify_correctly_redirect_on_respective_home_screen("beenish")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_jadwa_page.click_on_the_hide_portfolio_toggle_button_and_redirect_holistic_home()
#     update_jadwa_page.verify_portfolio_not_visible_on_holistic_home("beenish")

# def test_un_hide_conservative_portfolios():
#     """Case 4 Verify successfully remove the Conservative Portfolio from the hidden listing and display it again on the Holistic Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("beenish")
#     update_jadwa_page.verify_correctly_redirect_on_respective_home_screen("beenish")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_jadwa_page.click_on_the_hide_portfolio_toggle_button_and_redirect_holistic_home()
#     update_jadwa_page.verify_portfolio_not_visible_on_holistic_home("beenish")
#     update_jadwa_page.click_on_the_service_tab_and_proceed()
#     update_jadwa_page.scroll_down_on_service_screen_and_click_on_portfolio_management_option()
#     update_jadwa_page.scroll_down_to_find_hidden_portfolio_and_perform_click("beenish")
#     update_jadwa_page.click_on_the_toggle_button_to_off_the_toggle_and_remove_portfolio_from_hide_listing()
#     update_jadwa_page.click_on_the_back_button_to_redirect_the_portfolio_management_listing()
#     update_jadwa_page.click_back_button_and_move_to_service_home_screen()
#     update_jadwa_page.click_on_holistic_tab_and_proceed()
#     update_jadwa_page.verify_respective_portfolio_successfully_unhide("beenish")
#
# def test_hide_conservative_portfolio_value():
#     """Case 5 Verify successfully hide the Conservative Portfolio value on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("beenish")
#     update_jadwa_page.verify_redirect_on_respective_home_screen("beenish")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()

# def test_un_hide_conservative_portfolio_value():
#     """Case 6 Verify successfully unhide the Conservative Portfolio value and ensure the value in digits is displayed correctly on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("beenish")
#     update_jadwa_page.verify_redirect_on_respective_home_screen("beenish")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()
# ## moderate
# def test_update_moderate_portfolios_name():
#     """Case 1 Verify successfully update the moderate Portfolio name and display the new name on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_investment_portfolio = UpdateInvestmentPortfolios(driver)
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen("beenish")
#     update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen("beenish")
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_investment_portfolio.click_on_the_edit_option()
#     update_investment_portfolio.click_on_name_field_and_remove_to_update()
#     update_investment_portfolio.click_on_the_view_to_hide_keyboard()
#     update_investment_portfolio.click_on_icon_to_update()
#     update_investment_portfolio.click_on_save_button()
#     update_investment_portfolio.click_on_success_update_button()

# def test_update_moderate_portfolios_icon():
#     """Case 2 Verify successfully update the moderate Portfolio goal icon and display it correctly on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_investment_portfolio = UpdateInvestmentPortfolios(driver)
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen("Sarah")
#     update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen("Sarah")
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_investment_portfolio.click_on_the_edit_option()
#     update_investment_portfolio.click_on_name_field_and_remove_to_update()
#     update_investment_portfolio.click_on_the_view_to_hide_keyboard()
#     update_investment_portfolio.click_on_icon_to_update()
#     update_investment_portfolio.click_on_save_button()
#     update_investment_portfolio.click_on_success_update_button()

# def test_hide_moderate_portfolios():
#     """Case 3 Verify successfully hide the moderate Portfolio and ensure it is not visible on the Holistic Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("PortfolioDZA")
#     update_jadwa_page.verify_correctly_redirect_on_respective_home_screen("PortfolioDZA")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_jadwa_page.click_on_the_hide_portfolio_toggle_button_and_redirect_holistic_home()
#     update_jadwa_page.verify_portfolio_not_visible_on_holistic_home("PortfolioDZA")

# def test_un_hide_moderate_portfolios():
#     """Case 4 Verify successfully remove the moderate Portfolio from the hidden listing and display it again on the Holistic Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("PortfolioDZA")
#     update_jadwa_page.verify_correctly_redirect_on_respective_home_screen("PortfolioDZA")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_jadwa_page.click_on_the_hide_portfolio_toggle_button_and_redirect_holistic_home()
#     update_jadwa_page.verify_portfolio_not_visible_on_holistic_home("PortfolioDZA")
#     update_jadwa_page.click_on_the_service_tab_and_proceed()
#     update_jadwa_page.scroll_down_on_service_screen_and_click_on_portfolio_management_option()
#     update_jadwa_page.scroll_down_to_find_hidden_portfolio_and_perform_click("PortfolioDZA")
#     update_jadwa_page.click_on_the_toggle_button_to_off_the_toggle_and_remove_portfolio_from_hide_listing()
#     update_jadwa_page.click_on_the_back_button_to_redirect_the_portfolio_management_listing()
#     update_jadwa_page.click_back_button_and_move_to_service_home_screen()
#     update_jadwa_page.click_on_holistic_tab_and_proceed()
#     update_jadwa_page.verify_respective_portfolio_successfully_unhide("PortfolioDZA")

# def test_hide_moderate_portfolio_value():
#     """Case 5 Verify successfully hide the moderate Portfolio value on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("beenish")
#     update_jadwa_page.verify_redirect_on_respective_home_screen("beenish")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()
#
# def test_un_hide_moderate_portfolio_value():
#     """Case 6 Verify successfully unhide the moderate Portfolio value and ensure the value in digits is displayed correctly on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("PortfolioDZA")
#     update_jadwa_page.verify_redirect_on_respective_home_screen("PortfolioDZA")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()

# ## Growth
# def test_update_growth_portfolios_name():
#     """Case 1 Verify successfully update the growth Portfolio name and display the new name on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_investment_portfolio = UpdateInvestmentPortfolios(driver)
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen("beenish")
#     update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen("beenish")
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_investment_portfolio.click_on_the_edit_option()
#     update_investment_portfolio.click_on_name_field_and_remove_to_update()
#     update_investment_portfolio.click_on_the_view_to_hide_keyboard()
#     update_investment_portfolio.click_on_icon_to_update()
#     update_investment_portfolio.click_on_save_button()
#     update_investment_portfolio.click_on_success_update_button()

# def test_update_growth_portfolios_icon():
#     """Case 2 Verify successfully update the growth Portfolio goal icon and display it correctly on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_investment_portfolio = UpdateInvestmentPortfolios(driver)
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen("Muhammad")
#     update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen("Muhammad")
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_investment_portfolio.click_on_the_edit_option()
#     update_investment_portfolio.click_on_name_field_and_remove_to_update()
#     update_investment_portfolio.click_on_the_view_to_hide_keyboard()
#     update_investment_portfolio.click_on_icon_to_update()
#     update_investment_portfolio.click_on_save_button()
#     update_investment_portfolio.click_on_success_update_button()

# def test_hide_growth_portfolios():
#     """Case 3 Verify successfully hide the growth Portfolio and ensure it is not visible on the Holistic Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("PortfolioDZA")
#     update_jadwa_page.verify_correctly_redirect_on_respective_home_screen("PortfolioDZA")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_jadwa_page.click_on_the_hide_portfolio_toggle_button_and_redirect_holistic_home()
#     update_jadwa_page.verify_portfolio_not_visible_on_holistic_home("PortfolioDZA")

# def test_un_hide_growth_portfolios():
#     """Case 4 Verify successfully remove the growth Portfolio from the hidden listing and display it again on the Holistic Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("PortfolioADQ")
#     update_jadwa_page.verify_correctly_redirect_on_respective_home_screen("PortfolioADQ")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_alpaca_page.select_update_button_and_proceed()
#     update_jadwa_page.click_on_the_hide_portfolio_toggle_button_and_redirect_holistic_home()
#     update_jadwa_page.verify_portfolio_not_visible_on_holistic_home("PortfolioADQ")
#     update_jadwa_page.click_on_the_service_tab_and_proceed()
#     update_jadwa_page.scroll_down_on_service_screen_and_click_on_portfolio_management_option()
#     update_jadwa_page.scroll_down_to_find_hidden_portfolio_and_perform_click("PortfolioADQ")
#     update_jadwa_page.click_on_the_toggle_button_to_off_the_toggle_and_remove_portfolio_from_hide_listing()
#     update_jadwa_page.click_on_the_back_button_to_redirect_the_portfolio_management_listing()
#     update_jadwa_page.click_back_button_and_move_to_service_home_screen()
#     update_jadwa_page.click_on_holistic_tab_and_proceed()
#     update_jadwa_page.verify_respective_portfolio_successfully_unhide("PortfolioADQ")

# def test_hide_growth_portfolio_value():
#     """Case 5 Verify successfully hide the growth Portfolio value on the Conservative Portfolio Home Screen."""
#     driver = create_driver()
#     login_page = LoginPage(driver)
#     login_page.click_welcomescreen_next_buttons()
#     login_page.select_user()
#     login_page.enter_phone_number("535553454")
#     login_page.click_continue()
#     login_page.enter_password(password)
#     # login_page.enter_otp_code()
#     login_page.verify_holistic_home_screen()
#     update_jadwa_page = UpdateJadwaPortfolios(driver)
#     update_jadwa_page.scroll_and_select_portfolio("beenish")
#     update_jadwa_page.verify_redirect_on_respective_home_screen("beenish")
#     update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_hide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_hidden()
#     update_alpaca_page.click_on_update_button()
#     update_jadwa_page.click_on_unhide_portfolio_value_option()
#     update_jadwa_page.verify_portfolio_values_un_hidde()
#
def test_un_hide_growth_portfolio_value():
    """Case 6 Verify successfully unhide the growth Portfolio value and ensure the value in digits is displayed correctly on the Conservative Portfolio Home Screen."""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_jadwa_page = UpdateJadwaPortfolios(driver)
    update_jadwa_page.scroll_and_select_portfolio("PortfolioADQ")
    update_jadwa_page.verify_redirect_on_respective_home_screen("PortfolioADQ")
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_update_button()
    update_jadwa_page.click_on_hide_portfolio_value_option()
    update_jadwa_page.verify_portfolio_values_hidden()
    update_alpaca_page.click_on_update_button()
    update_jadwa_page.click_on_unhide_portfolio_value_option()
    update_jadwa_page.verify_portfolio_values_un_hidde()
    update_alpaca_page.click_on_update_button()
    update_jadwa_page.click_on_hide_portfolio_value_option()
    update_jadwa_page.verify_portfolio_values_hidden()
    update_alpaca_page.click_on_update_button()
    update_jadwa_page.click_on_unhide_portfolio_value_option()
    update_jadwa_page.verify_portfolio_values_un_hidde()
    update_alpaca_page.click_on_update_button()
    update_jadwa_page.click_on_hide_portfolio_value_option()
    update_jadwa_page.verify_portfolio_values_hidden()
    update_alpaca_page.click_on_update_button()
    update_jadwa_page.click_on_unhide_portfolio_value_option()
    update_jadwa_page.verify_portfolio_values_un_hidde()


