from abyan_project_automation.src.andriod.pages.kyc_peb_block_page import KycPebBlock
from abyan_project_automation.src.utils.randomdatagenerator import RandomDataGenerator


# Case# 1 :PEB question for has Worked On Financial
def test_kyc_with_nid_peb_questions_for_has_worked_on_financial(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_has_work_on_Financial() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_holistic_home_screen()
    peb_block_page.get_created_portfolio() #Done

# Case# 2 :PEB question related Experience
def test_kyc_with_nid_peb_questions_for_related_experience(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_related_experience() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_holistic_home_screen()
    peb_block_page.get_created_portfolio() #Done

# Case# 3 PEB question for has Worked On Financial and related Experience
def test_kyc_with_nid_peb_question_for_has_work_financial_and_related_experience(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_related_experience() # PEB Question
    peb_block_page.select_has_work_on_Financial() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_holistic_home_screen()
    peb_block_page.get_created_portfolio() #Done

# Case# 4: PEB question for membership Relevant, select grant no
def test_kyc_with_nid_peb_question_for_membership_relevant(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen() #Done

# Case# 5: PEB question for government Employee
def test_kyc_with_nid_peb_question_for_government_employee(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page = KycPebBlock(driver)
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed() # Addresses screen
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_government_employee() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen() #Done

# Case# 6: PEB question for relative government employee
def test_kyc_with_nid_peb_question_for_relative_government_employee(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page = KycPebBlock(driver)
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed() # Addresses screen
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_relative_government_employee() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen()

# Case# 7: PEB question for membership Relevant,and government Employee
def test_kyc_with_nid_peb_question_for_membership_relevant_and_government_employee(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.select_peb_question_for_government_employee()  # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen() #Done

# Case# 8: PEB question for membership Relevant,and relative government employee
def test_kyc_with_nid_peb_question_for_membership_relevant_and_relative_government_employee(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.select_peb_question_for_relative_government_employee()  # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen() #Done

# Case# 9: PEB question for membership Relevant, government Employee and relative government employee
def test_kyc_with_nid_peb_question_for_membership_relevant_and_govt_employee_and_relative_government_emp(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.select_peb_question_for_government_employee()  # PEB Question govt_employee_and_relative_government_emp
    peb_block_page.select_peb_question_for_relative_government_employee()  # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen() #Done

# Case# 10 :PEB question for membership Relevant, tax resident yes, inheritance yes, grant yes
def test_kyc_with_nid_peb_questions_for_has_worked_on_financial_yes_for_all_questions(driver):
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant()# PEB Question
    peb_block_page.select_peb_question_for_government_employee()  # PEB Question
    peb_block_page.select_peb_question_for_relative_government_employee()  # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_yes_and_proceed()
    peb_block_page.select_state_and_proceed()
    peb_block_page.select_continue_and_proceed()
    peb_block_page.select_tin_no()
    peb_block_page.select_other_and_fill_field()
    peb_block_page.select_inheritance_yes()
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    # peb_block_page.select_first_investing_outside()
    # peb_block_page.select_second_investing_outside()
    # peb_block_page.select_third_investing_outside()
    # peb_block_page.select_fourth_investing_outside()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next_btn()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next_btn()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next_btn()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.verify_under_review_screen() #Done

#Started
#Edit_EDD_Questions
def test_kyc_with_nid_edit_peb_question_for_membership_relevant(driver):
    """Verify editing of “Membership Relevant” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
         Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan not selected"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #edit
    peb_block_page.select_inheritance_yes() #inheritence from relatives yes
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.adjust_distribution_ratio()
    peb_block_page.select_invest_outside()
    peb_block_page.click_button()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()

def test_kyc_with_nid_edit_peb_question_for_government_employee(driver):
    """Verify editing of “government_employee” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
         Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan not selected"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_government_employee() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    # peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #edit
    peb_block_page.select_inheritance_yes() #inheritence from relatives yes
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.adjust_distribution_ratio()
    peb_block_page.select_invest_outside()
    peb_block_page.click_button()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()

def test_kyc_with_nid_edit_peb_question_for_relative_government_employee(driver):
    """Verify editing of “relative_government_employee” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
         Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan not selected"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_relative_government_employee() # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #edit
    peb_block_page.select_inheritance_yes() #inheritence from relatives yes
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.adjust_distribution_ratio()
    peb_block_page.select_invest_outside()
    peb_block_page.click_button()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()

def test_kyc_with_nid_edit_peb_question_for_membership_relevant_and_government_employee(driver):
    """Verify editing of “membership_relevant_and_government_employee” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
         Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan not selected"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.select_peb_question_for_government_employee()  # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #edit
    peb_block_page.select_inheritance_yes() #inheritence from relatives yes
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.adjust_distribution_ratio()
    peb_block_page.select_invest_outside()
    peb_block_page.click_button()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()

def test_kyc_with_nid_edit_peb_question_for_govt_employee_and_relative_government_emp(driver):
    """Verify editing of “govt_employee_and_relative_government_emp” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
         Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan not selected"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_government_employee()  # PEB Question
    peb_block_page.select_peb_question_for_relative_government_employee()  # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #edit
    peb_block_page.select_inheritance_yes() #inheritence from relatives yes
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.adjust_distribution_ratio()
    peb_block_page.select_invest_outside()
    peb_block_page.click_button()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()

def test_kyc_with_nid_edit_peb_question_for_membership_relevant_and_govt_employee_and_relative_government_emp(driver):
    """Verify editing of “membership_relevant_and_govt_employee_and_relative_government_emp” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
         Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan not selected"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.select_peb_question_for_government_employee()  # PEB Question
    peb_block_page.select_peb_question_for_relative_government_employee()  # PEB Question
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #edit
    peb_block_page.select_inheritance_yes() #inheritence from relatives yes
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.adjust_distribution_ratio()
    peb_block_page.select_invest_outside()
    peb_block_page.click_button()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()

#Edit_EDD_Questions
def test_kyc_with_nid_edit_peb_q_for_membership_relevant(driver):
    """Verify editing of “Membership Relevant” in PEB flow by updating answers for Tax residence, Inheritance, Grants,
     Investing outside Abyan, Financial institution, Current investment, and Annual investment."""
    """investing_outside_abyan yes"""
    peb_block_page = KycPebBlock(driver)
    peb_block_page.click_welcomescreen_next_buttons()
    peb_block_page.select_user()
    peb_block_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    peb_block_page.click_continue_next()
    peb_block_page.enter_otp_code()
    peb_block_page.enter_password()
    peb_block_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    peb_block_page.click_dob_field()
    peb_block_page.select_random_dob()
    peb_block_page.confirm_date()
    peb_block_page.click_continue()
    peb_block_page.verify_user_is_on_welcome_screen()
    peb_block_page.verify_user_is_on_address_screen()
    peb_block_page.select_random_city_and_proceed()
    peb_block_page.select_random_district_and_proceed()
    peb_block_page.verify_user_is_on_investment_screen()
    peb_block_page.select_knowledge_medium_and_proceed()
    peb_block_page.select_education_primary_and_proceed()
    peb_block_page.select_employment_student_and_proceed()
    peb_block_page.select_income_job_and_proceed()
    peb_block_page.select_social_status_single_and_proceed()
    peb_block_page.select_annual_income_option1_and_proceed()
    peb_block_page.select_net_worth_option1_and_proceed()
    peb_block_page.select_risk_ability_very_low_and_proceed()
    peb_block_page.select_investment_time_period_option1_and_proceed()
    peb_block_page.select_investment_goals_capital_growth_and_proceed()
    peb_block_page.select_yes_for_PEB()
    peb_block_page.select_peb_question_for_membership_relevant() # PEB Question
    peb_block_page.input_random_text_in_field_second()
    peb_block_page.click_button()
    peb_block_page.select_tax_resident_no_and_proceed()
    peb_block_page.select_inheritance_no()
    peb_block_page.select_grants_no()
    peb_block_page.select_investing_outside_abyan()
    peb_block_page.click_button()
    peb_block_page.input_financial_institution()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_two()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_three()
    peb_block_page.click_add_institution()
    peb_block_page.input_financial_institution_four()
    peb_block_page.select_next()
    peb_block_page.input_current_investment_value()
    peb_block_page.select_next()
    peb_block_page.input_expected_investment_annual()
    peb_block_page.select_next()
    peb_block_page.verify_user_is_on_email_screen()
    peb_block_page.enter_random_email()
    peb_block_page.button_continue()
    peb_block_page.select_create_button()
    peb_block_page.success_otp_code()
    peb_block_page.verify_under_review_screen()
    peb_block_page.click_refresh_page()
    peb_block_page.continue_to_edit() #Done
    peb_block_page.select_inheritance_yes() #inheritence from relatives
    peb_block_page.select_inheritance_year()
    peb_block_page.input_investment_value()
    peb_block_page.select_inheritance_types_and_proceed()
    peb_block_page.click_country_field()
    peb_block_page.select_random_inheritance_country()
    peb_block_page.select_next_btn()
    peb_block_page.select_grants_yes()
    peb_block_page.select_year_of_grant()
    peb_block_page.input_value_of_grant()
    peb_block_page.type_of_grant()
    peb_block_page.country_of_grant()
    peb_block_page.select_next_btn()
    peb_block_page.click_button()
    peb_block_page.remove_financial_institution_three()
    peb_block_page.remove_financial_institution_two()
    peb_block_page.remove_financial_institution_one()
    peb_block_page.select_next_btn()
    peb_block_page.remove_and_input_current_investment_value()
    peb_block_page.select_next_btn()
    peb_block_page.remove_and_input_expected_investment_annual()
    peb_block_page.select_next_btn()
    peb_block_page.click_success_edit_due_diligence()
    peb_block_page.click_refresh_page()



































