from abyan_project_automation.src.andriod.pages.cash_portfolios_creation_page import CreateCashPortfolios
from abyan_project_automation.src.andriod.pages.login_page import LoginPage
from abyan_project_automation.src.andriod.pages.update_cash_portfolios_page import UpdateCashPortfolios
from abyan_project_automation.src.constants.credentials import password
from abyan_project_automation.src.utils.driver_factory import create_driver


def test_update_pre_define_cash_portfolio_name():
    """case 1 Verify successfully update the cash "Pre-Defined Portfolio" name and ensure the home screen displays the updated name."""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("predefineportfo") # make sure to change portfolio name
    holistic_page.verify_pre_define_category_home_screen("predefineportfo")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon("predefineportfo")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    # update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()

def test_update_pre_define_cash_portfolios_icon():
    """case 2 Verify successfully update the cash "Pre-Defined Portfolio" icon and ensure the home screen displays the updated icon."""

    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("predefineportfo") # make sure to change portfolio name
    holistic_page.verify_pre_define_category_home_screen("predefineportfo")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon("predefineportfo")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    update_cash_page.click_edit_field_remove_existing_goal_amount_and_update_new_amount()
    update_cash_page.click_on_save_changes_button_and_proceed()

def test_update_pre_define_portfolio_goal_amount():
    """case 3 Verify successfully update the cash "Pre-Defined Portfolio" goal amount and ensure the home screen displays the updated goal amount."""

    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("CategoryIR")
    holistic_page.verify_pre_define_category_home_screen("CategoryIR")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon("CategoryIR")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    update_cash_page.click_edit_field_remove_existing_goal_amount_and_update_new_amount()
    update_cash_page.click_on_save_changes_button_and_proceed()

def test_update_flow_for_pre_define_cash_portfolio_delete():
    """case 4 Verify successfully delete the cash " Pre-Defined Portfolio" and ensure the cash portfolio no longer contains the deleted pre-defined portfolio."""

    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("CategoryM")
    holistic_page.verify_pre_define_category_home_screen("CategoryM")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon("CategoryM")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    # update_cash_page.verify_updated_category_name_visible()
    update_cash_page.click_edit_field_remove_existing_goal_amount_and_update_new_amount()
    update_cash_page.click_outside_and_hide_keyboard()
    update_cash_page.click_on_save_changes_button_and_proceed()
    update_cash_page.click_on_update_icon_to_delete()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_delete_category_button_and_proceed()
    update_cash_page.click_on_delete_button_to_delete_category()
    # update_cash_page.verify_user_should_redirect_to_the_holistic_home_screen_after_delete_category_and_verify_category_name_not_showing_that_previously_updated_name()

def test_update_custom_portfolio_name():
    """case 5 Verify successfully update the Cash "Custom Portfolio" name and display the updated name on the home screen."""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("tdgt")
    holistic_page.verify_pre_define_category_home_screen("tdgt")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon_for_custom_category("tdgt")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    update_cash_page.click_on_save_changes_button_and_proceed()

def test_update_custom_portfolio_icon():
    """case 6 Verify successfully update the cash "Custom Portfolio" icon and display the updated icon on the home screen."""

    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("CategoryY")
    holistic_page.verify_pre_define_category_home_screen("CategoryY")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon_for_custom_category("CategoryY")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    update_cash_page.click_edit_field_remove_existing_goal_amount_and_update_new_amount()
    update_cash_page.click_on_save_changes_button_and_proceed()

def test_update_custom_portfolio_goal_amount():
    """Verify successfully update the cash "Custom Portfolio" goal amount and display the updated goal amount on the home screen."""

    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("CategoryXTSO")
    holistic_page.verify_pre_define_category_home_screen("CategoryXTSO")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon_for_custom_category("CategoryXTSO")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    update_cash_page.click_edit_field_remove_existing_goal_amount_and_update_new_amount()
    update_cash_page.click_on_save_changes_button_and_proceed()

def test_custom_portfolio_delete():
    """Verify successfully delete the cash "Custom Portfolio" and ensure the Cash Primary Portfolio no longer contains it."""

    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_cash_page = UpdateCashPortfolios(driver)
    holistic_page = CreateCashPortfolios(driver)
    holistic_page.verify_cash_portfolio_home_screen()
    holistic_page.click_button_to_create_custom_category_and_proceed()
    update_cash_page.click_on_pre_define_category_and_verify_home_screen("d do")
    holistic_page.verify_pre_define_category_home_screen("d do")
    update_cash_page.click_on_update_icon()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_edit_icon_for_custom_category("d do")
    update_cash_page.click_edit_field_remove_existing_name_and_update_new_name()
    update_cash_page.click_outside_and_hide_keyboard()
    # update_cash_page.perform_scroll_down_on_portfolio_name_update_screen_and_procced()
    update_cash_page.click_action_on_update_the_icon_and_proceed()
    update_cash_page.click_next_button()
    # update_cash_page.verify_updated_category_name_visible()
    update_cash_page.click_edit_field_remove_existing_goal_amount_and_update_new_amount()
    update_cash_page.click_outside_and_hide_keyboard()
    update_cash_page.click_on_save_changes_button_and_proceed()
    update_cash_page.click_on_update_icon_to_delete()
    update_cash_page.click_on_update_button()
    update_cash_page.click_on_delete_category_button_and_proceed()
    update_cash_page.click_on_delete_button_to_delete_category()
    # update_cash_page.verify_user_should_redirect_to_the_holistic_home_screen_after_delete_category_and_verify_category_name_not_showing_that_previously_updated_name()



