import time



from appium.webdriver.webdriver import WebDriver
from abyan_project_automation.src.andriod.pages.kyc_flow_page import KYCFlow
from abyan_project_automation.src.constants.credentials import id_number
from abyan_project_automation.src.utils.randomdatagenerator import RandomDataGenerator


# Case1: Verify that KYC is successfully completed using NID and the portfolio type is assigned as Conservative/Amana.
def test_kyc_with_nid_assigned_conservative_portfolio(driver: WebDriver):
    kyc_page = KYCFlow(driver)
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case2: Verify that KYC is successfully completed using NID and the portfolio type is assigned as Moderate/Matwazna.
def test_kyc_with_nid_assigned_moderate_portfolio(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option2_and_proceed()
    kyc_page.select_net_worth_option2_and_proceed()
    kyc_page.select_risk_ability_low_and_proceed()
    kyc_page.select_investment_time_period_option2_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case3: Verify that KYC is successfully completed using NID and the portfolio type is assigned as Growth/Namo.
def test_kyc_with_nid_assigned_growth_portfolio(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_high_and_proceed()
    kyc_page.select_education_intermediate_and_proceed()
    kyc_page.select_employment_employed_and_proceed()
    kyc_page.select_income_inheritance_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option4_and_proceed()
    kyc_page.select_net_worth_option4_and_proceed()
    kyc_page.select_risk_ability_medium_and_proceed()
    kyc_page.select_investment_time_period_option2_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case4: Verify that KYC is successfully completed using NID and the portfolio type is assigned as Jadwa.
def test_kyc_with_nid_assigned_jadwa_portfolio(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_very_high_and_proceed()
    kyc_page.select_education_higher_and_proceed()
    kyc_page.select_employment_unemployed_and_proceed()
    kyc_page.select_income_family_and_proceed()
    kyc_page.click_continue()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option6_and_proceed()
    kyc_page.select_net_worth_option5_and_proceed()
    kyc_page.select_risk_ability_very_high()
    kyc_page.select_investment_time_period_option3_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case 5: Verify that the user can change the portfolio type to another option portfolio before final creation after initially assigning the portfolio.
def test_kyc_with_nid_assigned_jadwa_portfolio_but_change_portfolio_type(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_very_high_and_proceed()
    kyc_page.select_education_higher_and_proceed()
    kyc_page.select_employment_unemployed_and_proceed()
    kyc_page.select_income_family_and_proceed()
    kyc_page.click_continue()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option6_and_proceed()
    kyc_page.select_net_worth_option5_and_proceed()
    kyc_page.select_risk_ability_very_high_and_proceed()
    kyc_page.select_investment_time_period_option3_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.click_change_portfolio_type()
    kyc_page.select_conservative_type()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

def test_kyc_verify_valid_nid_and_proceed(driver):
    """Case6:Verify that entering a valid NID on the NID screen allows the user to proceed to the next step successfully."""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen() #Done

def test_kyc_verify_invalid_nid_and_proceed(driver):
    """Case7: Verify that entering an invalid NID on the NID screen displays the proper error message. """
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_invalid_Id_card_number(id_number)
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_continue()
    assert kyc_page.check_toast_in_logcat(expected_text = "رقم الهوية غير صحيح"), "Toast not captured in logcat"
    kyc_page.click_next() #Done

def test_kyc_verify_valid_nid_and_dob_hijri(driver):
    """Case8: Verify that selecting the Date of Birth in 'Hijri calendar' displays the selected date correctly on NID screen"""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.click_birthday_input()
    kyc_page.click_miladi_hijri_option()
    kyc_page.select_random_dob()
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen() #Done

def test_kyc_verify_valid_nid_and_dob_gregorian(driver):
    """Case9: Verify that selecting the Date of Birth in 'Gregorian calendar' displays the selected date correctly on NID screen"""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen() #Done

def test_kyc_verify_city_selection_drop_down(driver):
    """Case10: Verify that when a city is selected from the dropdown, the address screen correctly displays the chosen city."""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() #Done

def test_kyc_verify_district_selection_drop_down(driver):
    """Case11: Verify that when a district is selected from the dropdown, the address screen correctly displays the chosen district."""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed()
    kyc_page.select_random_district_and_proceed() #Done

def test_kyc_city_search_functionality(driver):
    """Case12: Verify that the search functionality in the city dropdown works correctly and the searched city is displayed in the address field on the screen."""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.click_city_field()
    kyc_page.type_in_city_search_bar("RIYADH")
    kyc_page.search_and_select_city()
    kyc_page.click_district_field()
    kyc_page.type_in_district_search_bar("King Abdullah Dist")
    kyc_page.search_and_select_dist()
    kyc_page.verify_user_is_on_investment_screen() #Done

def test_kyc_district_search_functionality(driver):
    """Case13: Verify that the search functionality in the district dropdown works correctly and the searched district is displayed in the address field on the screen."""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.click_city_field()
    kyc_page.type_in_city_search_bar("RIYADH")
    kyc_page.search_and_select_city()
    kyc_page.click_district_field()
    kyc_page.type_in_district_search_bar("King Abdullah Dist")
    kyc_page.search_and_select_dist()
    kyc_page.verify_user_is_on_investment_screen() #Done

def test_kyc_with_nid_select_investment_correct_answer(driver):
    """Case14:Verify that selecting the 'correct answer' on the Investment Knowledge screen in Interactive Lessons displays a success confirmation and allows the user to proceed."""
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_low_and_proceed()
    kyc_page.select_investment_correct_answer()
    kyc_page.click_next_btn()
    kyc_page.select_education_higher_and_proceed()
    kyc_page.select_employment_unemployed_and_proceed()
    kyc_page.select_income_family_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option6_and_proceed()
    kyc_page.select_net_worth_option5_and_proceed()
    kyc_page.select_risk_ability_very_high_and_proceed()
    kyc_page.select_investment_time_period_option3_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

def test_kyc_with_nid_select_investment_wrong_answer(driver):
    """ Case15: Verify that selecting the 'wrong answer' on the Investment Knowledge screen in Interactive Lessons displays a success confirmation and allows the user to proceed.
    """
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_low_and_proceed()
    kyc_page.select_investment_wrong_answer()
    kyc_page.click_next_btn()
    kyc_page.select_education_higher_and_proceed()
    kyc_page.select_employment_unemployed_and_proceed()
    kyc_page.select_income_family_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option6_and_proceed()
    kyc_page.select_net_worth_option5_and_proceed()
    kyc_page.select_risk_ability_very_high_and_proceed()
    kyc_page.select_investment_time_period_option3_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case16: Verify that entering employee details on the 'Employment Status screen' that displays all the entered information correctly, allowing the user to proceed.
def test_kyc_with_nid_verify_employment_status_fields(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed()
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_low_and_proceed()
    kyc_page.select_investment_correct_answer()
    kyc_page.click_next_btn()
    kyc_page.select_education_intermediate_and_proceed()
    kyc_page.select_employment_freelance_and_proceed()
    kyc_page.input_first_field()
    kyc_page.select_random_from_second_dropdown()
    kyc_page.input_third_field()
    kyc_page.input_four_field()
    kyc_page.click_next()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_high_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case17: Verify that selecting multiple options on the 'Source of Income screen' that displays all selected options correctly.

def test_kyc_with_nid_select_all_source_of_income_fields(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_all_income_sources_and_proceed()
    kyc_page.click_continue()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# #Case18: Verify that the input field for 'married' on the 'Marital Status screen' accepts user input and displays the entered details correctly.
def test_kyc_with_nid_marital_status_married_input_field(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_married_and_proceed()
    kyc_page.input_two_random_digits_in_field_and_process()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case19:Verify that the input field for 'Divorced' on the 'Marital Status screen' accepts user input and displays the entered details correctly.
def test_kyc_with_nid_marital_status_divorced_input_field(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_divorced_and_proceed()
    kyc_page.input_two_random_digits_in_field_and_process()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case20: Verify that the input field for 'Widowed' on the 'Marital Status screen' accepts user input and displays the entered details correctly.
def test_kyc_with_nid_marital_status_widowed_input_field(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_widow_and_proceed()
    kyc_page.input_two_random_digits_in_field_and_process()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio()  # Done

# Case21: Verify that selecting a 'state' in the 'tax residence screen' stores and displays the selected state successfully.
def test_kyc_with_nid_verify_tax_residence_select_state_from_drop_down(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()

# #Case22: Verify that searching for a state in the dropdown on the tax residence screen displays and allows selection of the correct state successfully.
def test_kyc_with_nid_verify_tax_residence_search_state_from_drop_down(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.click_city_field()
    kyc_page.type_in_city_search_bar("RIYADH")
    kyc_page.search_and_select_city()
    kyc_page.click_district_field()
    kyc_page.type_in_district_search_bar("King Abdullah Dist")
    kyc_page.search_and_select_dist()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.click_state_field()
    kyc_page.type_state_in_search_bar("United States")
    kyc_page.select_state()
    kyc_page.select_continue_and_proceed()
    kyc_page.select_tin_yes()
    kyc_page.enter_random_tin()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()

# Case23: Verify that selecting a 'state' in the 'tax residence screen' stores and displays the selected state successfully.
def test_kyc_with_nid_verify_tax_residence_search_state_from_drop_down(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()

# Case24: Verify that selecting tax residence yes and No for TIN allows input and displays the entered data correctly.
def test_kyc_with_nid_verify_tax_residence_yes_and_select_state(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()
    kyc_page.select_tin_no()
    kyc_page.select_other_and_fill_field()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case25: Verify that selecting Tax residence yes, and TIN yes allows input and displays the entered data correctly.
def test_kyc_with_nid_verify_tax_residence_yes_tin_no_and_select_state(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()
    kyc_page.select_tin_yes()
    kyc_page.enter_random_tin()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# # Case26: Verify that KYC is successfully completed using an email address with the domain @test.com.
def test_kyc_with_nid_verify_email_with_domain_one(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()
    kyc_page.select_tin_yes()
    kyc_page.enter_random_tin()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# Case27: Verify that KYC is successfully completed using an email address with the domain @hotmail.com
def test_kyc_with_nid_verify_email_with_domain_two(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()
    kyc_page.select_tin_yes()
    kyc_page.enter_random_tin()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_hotmail_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio()  # Done

# ##Case28: Verify that KYC is successfully completed using an email address with the domain @gmail.com
def test_kyc_with_nid_verify_email_with_domain_three(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_Nid_number_Saudi_user())
    kyc_page.select_birthday(12, 11, 1991)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_yes_and_proceed()
    kyc_page.select_state_and_proceed()
    kyc_page.select_continue_and_proceed()
    kyc_page.select_tin_yes()
    kyc_page.enter_random_tin()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_gmail_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio() #Done

# #iqama user and DOB and create jadwa portfolio
def test_kyc_with_iqama_assigned_jadwa_portfolio(driver):
    kyc_page = KYCFlow(driver)
    kyc_page.click_welcomescreen_next_buttons()
    kyc_page.select_user()
    kyc_page = KYCFlow(driver)
    kyc_page.enter_phone_number(RandomDataGenerator.generate_valid_saudi_number())
    kyc_page.click_continue()
    kyc_page.enter_otp_code()
    kyc_page.enter_password()
    kyc_page.enter_Id_card_number(RandomDataGenerator.generate_iqama_number_non_Saudi_user())
    kyc_page.select_non_saudi_birthday()
    kyc_page.select_year(1978)
    kyc_page.select_month_arabic()
    kyc_page.select_day(1)
    kyc_page.confirm_dob()
    kyc_page.click_next()
    kyc_page.verify_user_is_on_welcome_screen()
    kyc_page.verify_user_is_on_address_screen()
    kyc_page.select_random_city_and_proceed() # Addresses screen
    kyc_page.select_random_district_and_proceed()
    kyc_page.verify_user_is_on_investment_screen()
    kyc_page.select_knowledge_medium_and_proceed()
    kyc_page.select_education_primary_and_proceed()
    kyc_page.select_employment_student_and_proceed()
    kyc_page.select_income_job_and_proceed()
    kyc_page.select_social_status_single_and_proceed()
    kyc_page.select_annual_income_option1_and_proceed()
    kyc_page.select_net_worth_option1_and_proceed()
    kyc_page.select_risk_ability_very_low_and_proceed()
    kyc_page.select_investment_time_period_option1_and_proceed()
    kyc_page.select_investment_goals_capital_growth_and_proceed()
    kyc_page.click_button()
    kyc_page.select_tax_resident_no_and_proceed()
    kyc_page.verify_user_is_on_email_screen()
    kyc_page.enter_random_email()
    kyc_page.button_continue()
    kyc_page.select_create_button()
    kyc_page.success_otp_code()
    kyc_page.verify_holistic_home_screen()
    kyc_page.get_created_portfolio()
