from abyan_project_automation.src.andriod.pages.change_investment_portfolio_types_page import \
    ChangeInvestmentPortfoliosType
from abyan_project_automation.src.andriod.pages.login_page import LoginPage
from abyan_project_automation.src.constants.credentials import password, alpaca_moderate_portfolio_name, \
    alpaca_growth_portfolio_name, alpaca_conservative_portfolio_name
from abyan_project_automation.src.utils.driver_factory import create_driver


def test_change_alpaca_portfolios_type_from_moderate_to_growth():
    """case1: moderate to growth portfolio"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen(alpaca_moderate_portfolio_name)
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_moderate_portfolio_name)
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_alpaca_page.select_wallet_type_option_and_proceed()
    update_alpaca_page.select_continue_for_changing_wallet_type_and_proceed()
    update_alpaca_page.select_growth_portfolio_type_to_update_growth_portfolio_type()
    update_alpaca_page.click_on_create_portfolio_button_and_proceed()
    login_page.enter_otp_code()
    update_alpaca_page.click_on_wallet_management_button_on_success_screen()
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_moderate_portfolio_name)
    update_alpaca_page.scroll_until_other_details_button_and_click()
    update_alpaca_page.scroll_until_transactions_listing_and_click()
    update_alpaca_page.click_on_conservative_change_portfolio_type_tab()
    update_alpaca_page.verify_user_on_change_portfolio_screen()
    update_alpaca_page.verify_portfolio_type_changed_successfully()

def test_change_alpaca_portfolios_type_from_moderate_to_conservative():
    """case2: moderate_to_conservative portfolio"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_moderate_portfolio_and_verify_moderate_home_screen(alpaca_moderate_portfolio_name)
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_moderate_portfolio_name)
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_alpaca_page.select_wallet_type_option_and_proceed()
    update_alpaca_page.select_continue_for_changing_wallet_type_and_proceed()
    update_alpaca_page.select_conservative_portfolio_type_to_update_conservative_portfolio_type()
    update_alpaca_page.click_on_create_portfolio_button_and_proceed()
    login_page.enter_otp_code()
    update_alpaca_page.click_on_wallet_management_button_on_success_screen()
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_moderate_portfolio_name)
    update_alpaca_page.scroll_until_other_details_button_and_click()
    update_alpaca_page.scroll_until_transactions_listing_and_click()
    update_alpaca_page.click_on_conservative_change_portfolio_type_tab()
    update_alpaca_page.verify_user_on_change_portfolio_screen()
    update_alpaca_page.verify_portfolio_type_changed_successfully()

def test_change_alpaca_portfolios_type_from_growth_to_moderate():
    """case3: growth_to_moderate portfolio"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_growth_portfolio_and_verify_growth_home_screen(alpaca_growth_portfolio_name)
    update_alpaca_page.verify_alpaca_growth_portfolio_home_screen(alpaca_growth_portfolio_name)
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_alpaca_page.select_wallet_type_option_and_proceed()
    update_alpaca_page.select_continue_for_changing_wallet_type_and_proceed()
    update_alpaca_page.select_moderate_portfolio_type_to_update_moderate_portfolio_type()
    update_alpaca_page.click_on_create_portfolio_button_and_proceed()
    login_page.enter_otp_code()
    update_alpaca_page.click_on_wallet_management_button_on_success_screen()
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_growth_portfolio_name)
    update_alpaca_page.scroll_until_other_details_button_and_click()
    update_alpaca_page.scroll_until_transactions_listing_and_click()
    update_alpaca_page.click_on_moderate_change_portfolio_type_tab()
    update_alpaca_page.verify_user_on_change_portfolio_screen()

def test_change_alpaca_portfolios_type_from_growth_to_conservative():
    """case4: growth_to_conservative portfolio"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_conservative_portfolio_and_verify_conservative_home_screen(alpaca_growth_portfolio_name)
    update_alpaca_page.verify_alpaca_conservative_portfolio_home_screen(alpaca_growth_portfolio_name)
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_alpaca_page.select_wallet_type_option_and_proceed()
    update_alpaca_page.select_continue_for_changing_wallet_type_and_proceed()
    update_alpaca_page.select_conservative_portfolio_type_to_update_conservative_portfolio_type()
    update_alpaca_page.click_on_create_portfolio_button_and_proceed()
    login_page.enter_otp_code()
    update_alpaca_page.click_on_wallet_management_button_on_success_screen()
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_growth_portfolio_name)
    update_alpaca_page.scroll_until_other_details_button_and_click()
    update_alpaca_page.scroll_until_transactions_listing_and_click()
    update_alpaca_page.click_on_conservative_change_portfolio_type_tab()
    update_alpaca_page.verify_user_on_change_portfolio_screen()

def test_change_alpaca_portfolios_type_from_conservative_to_growth():
    """case5: conservative_to_growth portfolio"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_conservative_portfolio_and_verify_conservative_home_screen(alpaca_conservative_portfolio_name)
    update_alpaca_page.verify_alpaca_conservative_portfolio_home_screen(alpaca_conservative_portfolio_name)
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_alpaca_page.select_wallet_type_option_and_proceed()
    update_alpaca_page.select_continue_for_changing_wallet_type_and_proceed()
    update_alpaca_page.select_growth_portfolio_type_to_update_growth_portfolio_type()
    update_alpaca_page.click_on_create_portfolio_button_and_proceed()
    login_page.enter_otp_code()
    update_alpaca_page.click_on_wallet_management_button_on_success_screen()
    update_alpaca_page.verify_alpaca_growth_portfolio_home_screen(alpaca_conservative_portfolio_name)
    update_alpaca_page.scroll_until_other_details_button_and_click()
    update_alpaca_page.scroll_until_transactions_listing_and_click()
    update_alpaca_page.click_on_growth_change_portfolio_type_tab()
    update_alpaca_page.verify_user_on_change_portfolio_screen()

def test_change_alpaca_portfolios_type_from_conservative_to_moderate():
    """case6: conservative_to_moderate portfolio"""
    driver = create_driver()
    login_page = LoginPage(driver)
    login_page.click_welcomescreen_next_buttons()
    login_page.select_user()
    login_page.enter_phone_number("535553454")
    login_page.click_continue()
    login_page.enter_password(password)
    # login_page.enter_otp_code()
    login_page.verify_holistic_home_screen()
    update_alpaca_page = ChangeInvestmentPortfoliosType(driver)
    update_alpaca_page.click_on_alpaca_conservative_portfolio_and_verify_conservative_home_screen(alpaca_conservative_portfolio_name)
    update_alpaca_page.verify_alpaca_conservative_portfolio_home_screen(alpaca_conservative_portfolio_name)
    update_alpaca_page.click_on_update_button()
    update_alpaca_page.select_update_button_and_proceed()
    update_alpaca_page.select_wallet_type_option_and_proceed()
    update_alpaca_page.select_continue_for_changing_wallet_type_and_proceed()
    update_alpaca_page.select_moderate_portfolio_type_to_update_moderate_portfolio_type()
    update_alpaca_page.click_on_create_portfolio_button_and_proceed()
    login_page.enter_otp_code()
    update_alpaca_page.click_on_wallet_management_button_on_success_screen()
    update_alpaca_page.verify_alpaca_moderate_portfolio_home_screen(alpaca_conservative_portfolio_name)
    update_alpaca_page.scroll_until_other_details_button_and_click()
    update_alpaca_page.scroll_until_transactions_listing_and_click()
    update_alpaca_page.click_on_moderate_change_portfolio_type_tab()
    update_alpaca_page.verify_user_on_change_portfolio_screen()

